name: Install serie

on:
  push:
    branches:
      - '*'
    paths:
      - serie.rb
      - .github/workflows/install-serie.yml

jobs:
  install:
    strategy:
      matrix:
        targets:
          - macos-12 # x86_64
          - macos-14 # aarch64
    runs-on: ${{ matrix.targets }}
    steps:
      - name: Run brew install
        run: brew install lusingander/tap/serie
      - name: Test
        run: serie --version
