name: Install stu

on:
  push:
    branches:
      - '*'
    paths:
      - stu.rb
      - .github/workflows/install-stu.yml

jobs:
  install:
    strategy:
      matrix:
        targets:
          - ubuntu-24.04 # x86_64
          - macos-13 # x86_64
          - macos-14 # aarch64
    runs-on: ${{ matrix.targets }}
    steps:
      # https://github.com/actions/runner-images/issues/6283
      - name: Setup homebrew
        if: runner.os == 'Linux'
        uses: Homebrew/actions/setup-homebrew@master
      - name: Run brew install
        run: brew install lusingander/tap/stu
      - name: Test
        run: stu --version
