name: Install ddv

on:
  push:
    branches:
      - '*'
    paths:
      - ddv.rb
      - .github/workflows/install-ddv.yml

jobs:
  install:
    strategy:
      matrix:
        targets:
          - macos-15-intel # x86_64
          - macos-15 # aarch64
    runs-on: ${{ matrix.targets }}
    steps:
      - name: Run brew install
        run: brew install lusingander/tap/ddv
      - name: Test
        run: ddv --version
